title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              http://njumrz.github.io
signoff:          njumrz
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://njumrz.github.io
    external:     true
  - name:         Email
    url:          mailto:njumrz@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/njumrz
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
